//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pyrenaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int id { get; set; }
        public string objet { get; set; }
        public string contenu { get; set; }
        public Nullable<System.DateTime> date_m { get; set; }
        public int id_Utilisateur { get; set; }
        public int id_Action { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
