//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pyrenaction.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pyrenactionEntities : DbContext
    {
        public pyrenactionEntities()
            : base("name=pyrenactionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Famille> Famille { get; set; }
        public virtual DbSet<Importance> Importance { get; set; }
        public virtual DbSet<Lien> Lien { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Questionnaire> Questionnaire { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<Tache> Tache { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
