//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pyrenaction.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pyrenactionEntities : DbContext
    {
        public pyrenactionEntities()
            : base("name=pyrenactionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Famille> Familles { get; set; }
        public virtual DbSet<Importance> Importances { get; set; }
        public virtual DbSet<Lien> Liens { get; set; }
        public virtual DbSet<Mail> Mails { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Questionnaire> Questionnaires { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Tache> Taches { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
